### ISSUE TITLE
Full width tables

### ISSUE THREAD

**Issue by lf-araujo** [duzyn/tufte-markdown#1]
Thank you for this code, it really is impressive. I am used to rmarkdown, but I prefer to work with pure pandoc and this code allows that. 

One request, though:

- Is it possible to support full width longtables with this template?

**Comment by duzyn** [comment]
With help of third party scripts, eg. [csv2html](https://github.com/dbohdan/csv2html) and [tably](https://github.com/narimiran/tably), you can convert a CSV table to HTML and LaTeX, then pipe to pp and Pandoc to generate a fullwidth table in HTML and PDF.

You can check out by my [example](https://github.com/duzyn/tufte-markdown/tree/master/fullwidthtable). Maybe it's helpful to you.

**Comment by lf-araujo** [comment]
Thank you! That is awesome! 

I forked your repository and incorporated several changes to the style you created, but instead of using tufte, I used memoir, have a look. The output turned out to work very well. I acknowledged you too.

Will try to add that as well.

**Comment by serussell** [comment]
Is there any way to do it with embedded tables, where the table content is not in a separate CSV file?  pandoc (markdown?) doesn't support classes on tables, and I haven't been able to find a filter or preprocessor for this.  Is my only option to hack the .tex and get fullwidth on all tables?
