### ISSUE TITLE
Error when convert to html and md

### ISSUE THREAD

**Issue by renpj** [duzyn/tufte-markdown#3]
Hi, it is very glad to find this repo, thanks for your work @duzyn 
I got trouble when I was trying to run the examples.  When I ran 
`pp -html -import=./pp-macros/html/common/today.html.pp README.pp.md > test.md`, I got the error: 
> pp.exe: Error while executing `bash C:\Users\ren\AppData\Local\Temp\pp1147829358.sh`: fd:3: hGetContents: invalid argument (invalid byte sequence)

However, the example of PDF is OK.  I guess it is the problem of pp. But I don't know how to solve it.
Thanks.

My env is: Win 10 + Miniconda 3 + Git Bash/MobaXterm

**Comment by duzyn** [comment]
I have fixed this issue. Now I use cmd to get current date from system on windows now.
